name: Personal porfolio

defaults:
    - scope:
        path: _en
        type: en
      values:
        layout: default
        permalink: /en
        sectionid: en

    - scope:
        path: _es
        type: es
      values:
        layout: default
        permalink: /es
        sectionid: es

collections:
    en:
    es:
        output: true
